version: '3.8'

services:
  db:
    image: postgres
    container_name: reforward_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  redis:
    image: redis
    container_name: reforward_redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_django
    command: bash -c "python manage.py migrate && python manage.py runserver --noreload 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_bot
    command: python run_bot.py
    env_file:
      - ./.env
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_celery
    command: celery -A reforward worker --loglevel=INFO
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_beat
    command: celery -A reforward beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data:
