version: '3.8'

services:
  db:
    image: postgres
    container_name: reforward_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  redis:
    image: redis
    container_name: reforward_redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_django
    command: bash -c "python manage.py migrate && gunicorn --bind :8000 --workers 2 --worker-class uvicorn.workers.UvicornWorker reforward.asgi:application"
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db

  userbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_userbot
    command: python run_userbot.py
    volumes:
      - ./sessions:/code/sessions
    env_file:
      - ./.env
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_celery
    command: celery -A reforward worker --loglevel=INFO
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reforward_beat
    command: celery -A reforward beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data:
