# Generated by Django 4.2.3 on 2023-12-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("username", models.CharField(blank=True, max_length=32, null=True)),
                ("first_name", models.CharField(blank=True, max_length=256, null=True)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("deep_link", models.CharField(blank=True, max_length=64, null=True)),
                ("is_blocked_bot", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("N", "Don't know")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("latest_meme_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
