# Generated by Django 4.2.3 on 2023-12-22 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("a_chat_id", models.BigIntegerField()),
                ("b_chat_id", models.BigIntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("A", "A -> B"), ("B", "B -> A"), ("X", "A <-> B")],
                        max_length=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notify_a", models.BooleanField(default=False)),
                ("notify_b", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forwarding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_message_id", models.BigIntegerField()),
                ("new_message_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tgbot.rule"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_general", models.BooleanField(default=False)),
                ("regex", models.CharField(max_length=512)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("R", "Replace"),
                            ("S", "Skip forwarding"),
                            ("D", "Disable rule"),
                        ],
                        default="R",
                        max_length=1,
                    ),
                ),
                (
                    "replacement",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.rule",
                    ),
                ),
            ],
        ),
    ]
