# Generated by Django 4.2.3 on 2023-12-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0003_rule_name_alter_rule_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tgbot.folder",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tgbot.folder",
            ),
        ),
    ]
