# Generated by Django 4.2.3 on 2023-12-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_folder_parent_alter_rule_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='bottom_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='top_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
