# Generated by Django 4.2.3 on 2023-12-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_rule_bottom_signature_rule_top_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forwarding_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
