# Generated by Django 4.2.8 on 2024-01-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_user_is_forwarding_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='is_general',
        ),
        migrations.AddField(
            model_name='filter',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
