# Generated by Django 4.2.8 on 2024-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_filter_is_general_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='signature_direction',
            field=models.CharField(choices=[('AB', 'A -> B'), ('BA', 'B -> A'), ('X', 'A <-> B')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='rule',
            name='direction',
            field=models.CharField(choices=[('O', 'One-way'), ('X', 'Two-way')], default='O', max_length=1),
        ),
    ]
