# Generated by Django 4.2.8 on 2024-01-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_rule_signature_direction_alter_rule_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='direction',
            field=models.CharField(choices=[('O', 'A -> B'), ('X', 'A <-> B')], default='X', max_length=1),
        ),
    ]
