# Generated by Django 4.2.8 on 2024-01-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_alter_rule_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterTriggerTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('trigger', models.CharField(max_length=1024)),
            ],
        ),
    ]
