# Generated by Django 4.2.8 on 2024-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_filtertriggertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='notify_myself',
            field=models.BooleanField(default=True),
        ),
    ]
