# Generated by Django 4.2.8 on 2024-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_rule_notify_myself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtertriggertemplate',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
