# Generated by Django 4.2.8 on 2024-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_rule_allow_a_chat_members_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='signature_direction',
            field=models.CharField(blank=True, choices=[('AB', 'A -> B'), ('BA', 'B -> A'), ('X', 'A <-> B')], default='AB', max_length=2, null=True),
        ),
    ]
