# Generated by Django 4.2.10 on 2024-02-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_alter_rule_signature_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroupForwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_group_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.rule')),
            ],
        ),
    ]
